apiVersion: apps/v1
kind: Deployment
metadata:
    name: mindbox-app
    namespace: mindbox
spec:
    replicas: 2
    selector:
        matchLabels:
            app: my-app
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: my-app
        spec:
            containers:
              - name: app-container
                image: # нужный нам образ
                ports:
                    - containerPort: 8080
                resources:
                    requests:
                        cpu: "100m"
                        memory: "128Mi"
                    limits:
                        cpu: "500m"
                        memory: "256Mi"
                readinessProbe:
                    httpGet:
                        path: /health
                        port: 8080
                    initialDelaySeconds: 10
                    periodSeconds: 5
                    failureThreshold: 3
                    timeoutSeconds: 2
