apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: my-app-hpa
    namespace: mindbox
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: mindbox-app
    minReplicas: 1
    maxReplicas: 6
    metrics:
        - type: Resource
          resource:
            name: cpu
            target:
                type: Utilization
                averageUtilization: 70
    behavior:
        scaleUp:
            stabilizationWindowSeconds: 0
            policies:
                - type: Percent
                  value: 100
                  periodSeconds: 10
        scaleDown:
            stabilizationWindowSeconds: 300           
            policies:
                - type: Percent
                  value: 50
                  periodSeconds: 20
