apiVersion: v1
kind: Service
metadata:
    name: my-app-service
    namespace: mindbox
spec:
    selector:
        app: my-app
    ports:
        - port: 80
          targetPort: 8080
    type: ClusterIP
